name: chaoperty
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3
  cupertino_stepper: ^0.2.1
  im_stepper: ^1.0.1+1
  slide_switcher: ^1.1.2
  auto_size_text: ^3.0.0
  dropdown_button2: ^1.8.9
  flutter_admin_scaffold: ^1.2.0
  side_sheet: ^1.0.3
  # scroll_pos: ^0.3.0
  # flutter_easy_table: ^0.0.1+1
  # pluto_grid: ^5.4.8
  # data_tables: ^1.4.0
  # responsive_table: ^0.2.0+2
  # expandable_datatable: ^0.0.6
  # listview_ex: ^0.0.2
  grouped_buttons_ns: ^1.0.0
  iconsax: ^0.0.8
  flutter_limited_checkbox: ^0.0.1
  radio_grouped_buttons: ^1.0.1
  group_radio_button: ^1.3.0
  shared_preferences: ^2.0.15
  fl_pin_code: ^0.0.9
  random_string: ^2.3.1
  email_otp: ^1.0.4
  # email_auth: ^1.0.0
  tap_debouncer: ^2.0.2
  image_picker: ^0.8.9
  file_picker: ^5.2.2
  # mysql1: ^0.20.0
  # date_time_picker: ^2.1.0
  printing: ^5.11.0
  syncfusion_flutter_xlsio: ^20.4.43-beta
  file_saver: ^0.1.1
  permission_handler: ^10.2.0
  syncfusion_flutter_datagrid_export: ^20.4.43-beta
  excel_dart: ^3.0.0
  excel: ^2.0.1
  pdf: ^3.8.4
  syncfusion_flutter_pdf: ^20.4.44
  # font_awesome_flutter: ^10.3.0
  # file_cryptor: ^0.0.3
  path_provider: ^2.0.6
  # buddhist_datetime_dateformat_sns: ^1.0.6
  webviewx: ^0.2.2
  intl: ^0.18.0
  http: ^0.13.5
  crypto: ^3.0.2
  pretty_qr_code: ^2.0.3
  flutter_multi_formatter: ^2.11.1
  simple_barcode_scanner: ^0.0.8
  # fast_image_resizer: ^0.0.2
  responsive_grid_list: ^1.3.2
  image_downloader_web: ^2.0.2
  device_marketing_names: ^0.6.5
  dart_ipify: ^1.1.1
  # syncfusion_flutter_signaturepad: ^20.4.54
  # hand_signature: ^3.0.1
  syncfusion_flutter_pdfviewer: ^20.4.54
  flutter_localization: ^0.1.12
  # widgets_to_image: ^0.0.2
  syncfusion_flutter_barcodes: any
  screenshot: ^2.1.0
  # dart_barcode: ^2.0.0
  path_drawing: ^1.0.1
  html_widget: ^0.0.3
  flutter_html_to_pdf: ^0.7.0
  image: ^4.0.17
  # flutter_image_compress: ^2.0.4
  # web_image_downloader: ^1.0.1
  universal_html: ^2.0.8 
  syncfusion_flutter_charts: any
  marquee: ^2.2.3
  drag_and_drop_lists: ^0.3.3
  flutter_popup_menu_button: ^0.0.1+5
  popup_menu_plus: ^0.0.5
  otp_timer_button: ^1.1.0
  flutter_gbprimepay_qrcode: ^0.0.5
  # quill_html_editor: ^0.1.5
  flutter_widget_from_html_core: ^0.10.6
  htmltopdfwidgets: ^0.0.9+1
  html_editor_enhanced: ^2.5.1
  # html_editor_enhanced_fork: ^2.5.1
  puppeteer: ^3.2.0
  html: ^0.15.4
  # xpath_selector_html_parser: ^3.0.1
  html_main_element: ^2.1.0
  dio: ^5.3.3
  get_ip_address: ^0.0.5
  usb_device: ^1.0.2
  percent_indicator: ^4.2.3
  upi_payment_qrcode_generator: ^1.4.0
  qr_flutter: ^4.0.0
  carousel_slider: ^4.2.1
  scrollview_observer: ^1.19.0
  connectivity_plus: ^5.0.2
  appflowy_editor: ^0.1.12
  month_year_picker: ^0.3.0+1
  flutter_chat_bubble: ^2.0.2
  chat_bubbles: ^1.5.0
  cached_network_image: ^3.3.1
  my_popup_menu: ^3.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/data00.htm
    - images/data001.html
    - images/
    - images/TP1/
    - images/TP2/
    - images/TP3/
    - images/TP4/
    - images/TP4_1/
    - images/LogoBank/
    - images/card/
    - images/audio/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: ThaiFont
      fonts:
        - asset: fonts/Sarabun-Medium.ttf
        - asset: fonts/Sarabun-Light.ttf
        - asset: downloadFile/ใบเสนอราคาdownloadFile.pdf


    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Bangers
      fonts:
        - asset: fonts/Bangers-Regular.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700

    - family: LINESeed1
      fonts:
        - asset: fonts/LINESeedSansTH_XBd.ttf

    - family: LINESeed2
      fonts:
        - asset: fonts/LINESeedSansTH_Rg.ttf
        
    - family: MaliExtra
      fonts:
        - asset: fonts/MaliExtraLight.ttf

    - family: THSarabunNew
      fonts:
        - asset: fonts/THSarabunNew.ttf

    - family: DoHyeon
      fonts:
        - asset: fonts/DoHyeon-Regular.ttf

    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf

    - family: Saysettha
      fonts:
        - asset: fonts/Saysettha-OT.ttf

    - family: Phetsarath
      fonts:
        - asset: fonts/Phetsarath-OT.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
